### ISSUE TITLE
Complete Remaining AutoTests

### ISSUE THREAD

**Issue by ptvrajsk** [CS2103-AY1819S2-T12-4/main#217]

**Comment by WeiTangLau** [comment]
## ~Command Package [Tackled by: @jetkan-yk @WeiTangLau @ptvrajsk]~
- [x] RenameCommandTest
- [x] DeleteCommandTest
- [x] DecryptCommandTest
- [x] EditPdfDescriptorTest
- [x] EncryptCommandTest
- [x] ExitCommandTest
- [x] FindCommandTest
- [x] HelpCommandTest
- [x] HistoryCommandTest
- [x] ListCommandTest
- [x] MergeCommandTest
- [x] RedoCommandTest
- [x] SelectCommandTest
- [x] TagCommandTest
- [x] UndoCommandTest
- [x] DeadlineCommandTest

## ~Command Parser Package [Tackled By: @WeiTangLau]~
- [x] PdfBookParserTest
- [x] ArgumentTokenizerTest
- [x] CommandParserTestUtil
- [x] DeadlineCommandParserTest
- [x] DecryptCommandParserTest
- [X] EncryptCommandParserTest
- [x] FindCommandParserTest
- [x] MergeCommandParserTest
- [x] ParserUtilTest
- [x] SelectCommandParserTest
- [x] TagCommandParserTest

## ~Logic Test [Tackled By: @jetkan-yk ]~
- [x] CommandHistoryTest
- [x] LogicManagerTest

## ~Storage Test [Tackled by @ptvrajsk]~
- [x] JsonAdaptedPdfTest
- [x] JsonPdfBookStorageTest
- [x] JsonSerializablePdfBookTest
- [x] JsonUserPrefStorageTest
- [x] StorageManagerTest

## ~model Package [Tackled By: @ptvrajsk @WeiTangLau ]~
- [x] ModelManagerTest
- [x] PdfBookTest
- [x] UserPrefsTest
- [x] VersionedPdfBookTest (Do we still need since we are not allowing for undo/redo?)

## ~model.tag Package [Tackled By: @ptvrajsk]~
- [x] TagTest

## ~model.pdf Package [Tackled By: @ptvrajsk & @WeiTangLau ]~
- [x] DeadlineTest
- [x] DirectoryTest
- [x] NameContainsKeywordsPredicateTest
- [x] NameTest
- [x] PdfTest
- [x] SizeTest
- [x] UniquePdfListTest
- [x] TagContainsKeywordsPredicateTest

**Comment by ptvrajsk** [comment]
# AutoTest Approach
## Workflow
1. Before starting on _**ANY**_ of the test files, please make a comment in this issue stating clearly which test file you are starting to work on so that we can easily track each others progress and avoid having 2 people working on the same test file at the same time.
2. Make Incremental commits on each test file. Every commit should only contain changes tied to one test file. (e.g. changes to `CommandTestUtil.java` & `AddCommandTest.java` can be under the same commit if your changes in `CommandTestUtil.java` is to allow `AddCommandTest.java` to work. So this commit will be considered as changes for the `AddCommandTest.java` to work.)
3. After completing each test file (after confirming that it works and passes all style checks). Ensure that your commit message contains the #217 so that Github automatically links your commit to this issue. Should there be any code problems this will allow us to refer to the problem and fix it easily.
**NOTE**: _**DO NOT**_ include the statement `resolve: #217` or `resolves: #217` in your commits or PR because Github will automatically close this issue if you do.
4. After your PR has been reviewed and merge, return to this issue and tick off the task that you have completed in https://github.com/CS2103-AY1819S2-T12-4/main/issues/217#issuecomment-480472280. Again, this will just assist house keeping.

**NOTE**: There maybe some test cases that work right out the box. In that case you can lump them together in a single commit. So for example if TestA and TestB is already working but TestC is not. When making changes to TestC we can just put that `Verified TestA & TestB working. Working on TestC` along those lines.

## Deadline
We should try to get this done BY _**Friday (12 April 2019)**_. So that we have the weekend to settle UG, DG & PPP.

**Comment by ptvrajsk** [comment]
~I'm currently starting NameTest, SizeTest & DirectoryTest. (model.pdf Package)~
~Awaiting PR Merger~
Merged

**Comment by ptvrajsk** [comment]
~Currently working on NameContainsKeywordsTest, DeadlineTest, Unique PdfListTest, TagTest~
~Awaiting PR Merger~
Merged

**Comment by WeiTangLau** [comment]
~I am currently working PdfTest & ModelManagerTest~
Merged

**Comment by ptvrajsk** [comment]
~Currently working on UserPrefsTest & PdfBookTest & VersionedPdfBookTest~
Merged

**Comment by lormee94** [comment]
Starting on Encrypt and Decrypt command test

**Comment by ptvrajsk** [comment]
~Starting JsonAdaptedPdfTest & JsonPdfBookStorageTest~
Merged

**Comment by jetkan-yk** [comment]
Currently working on deadlineCommandTest

**Comment by ptvrajsk** [comment]
~Working on TagCommandTest & TagCommandParserTest~
Merged
