### ISSUE TITLE
Sort command - sorting based on names is not user friendly

### ISSUE THREAD

**Issue by jetkan-yk** [CS2103-AY1819S2-T12-4/main#287]
The command `sort name up/down` sorts files based on ASCII alphabetical order, i.e. files with starting capital letter first, instead of dictionary alphabetical order, which causes sorting result to be not user-friendly. 

For instance (current):
-`Homework 1`
-`creative ideas`
-`lecture_note`

will be displayed instead of (preferred):
-`creative ideas`
-`Homework 1`
-`lecture_note`

which is more user-friendly.

**Comment by WeiTangLau** [comment]
Good job finding the bug. I think the reason for the bug is that we take the full name (including upper and lower cases) of the file as the argument. Instead, we should convert the argument to lower case / upper case then use that converted string for comparison to sort the pdfs. Hope this solves your problem. Let me know again should there be any other bug. Thanks!
